### ISSUE TITLE
Package using Angular Package Format

### ISSUE THREAD

**Issue by MRamos62786** [leolorenzoluis/xyz.MonacoEditorLoader#24]
When building my application using the Angular CLI, I get module build errors and instructions to submit this issue:

**The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).**

Actual Errors:

`ERROR in ./node_modules/@abc.xyz/angular-monaco-editor-loader/lib/monaco-editor-loader/monaco-editor-loader.directive.ts
Module build failed: Error: C:\Users\Marco Ramos\Documents\webapi-playground-app\node_modules\@abc.xyz\angular-monaco-editor-loader\lib\monaco-editor-loader\monaco-editor-loader.directive.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (C:\Users\Marco Ramos\Documents\webapi-playground-app\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:674:23)
    at plugin.done.then (C:\Users\Marco Ramos\Documents\webapi-playground-app\node_modules\@ngtools\webpack\src\loader.js:467:39)
    at process._tickCallback (internal/process/next_tick.js:109:7)
ERROR in ./node_modules/@abc.xyz/angular-monaco-editor-loader/lib/monaco-editor-loader/monaco-editor-loader.module.ts
Module build failed: Error: C:\Users\Marco Ramos\Documents\webapi-playground-app\node_modules\@abc.xyz\angular-monaco-editor-loader\lib\monaco-editor-loader\monaco-editor-loader.module.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (C:\Users\Marco Ramos\Documents\webapi-playground-app\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:674:23)
    at plugin.done.then (C:\Users\Marco Ramos\Documents\webapi-playground-app\node_modules\@ngtools\webpack\src\loader.js:467:39)
    at process._tickCallback (internal/process/next_tick.js:109:7)
ERROR in ./node_modules/@abc.xyz/angular-monaco-editor-loader/lib/monaco-editor-loader/monaco-editor-loader.service.ts
Module build failed: Error: C:\Users\Marco Ramos\Documents\webapi-playground-app\node_modules\@abc.xyz\angular-monaco-editor-loader\lib\monaco-editor-loader\monaco-editor-loader.service.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (C:\Users\Marco Ramos\Documents\webapi-playground-app\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:674:23)
    at plugin.done.then (C:\Users\Marco Ramos\Documents\webapi-playground-app\node_modules\@ngtools\webpack\src\loader.js:467:39)
    at process._tickCallback (internal/process/next_tick.js:109:7)`

Thanks

**Comment by leolorenzoluis** [comment]
How are you referencing this? Could you show your code

**Comment by leolorenzoluis** [comment]
Interesting, it should not deploy the typescript files in npm. The example usage is working fine without explicitly calling /dist.
